from __future__ import annotations

import sys

from autotrade.config import load_settings
from autotrade.logging_utils import append_jsonl_log, append_text_log


HISTORICAL_RECORDS = [
    {
        "timestamp": "2026-04-24T10:24:02-04:00",
        "source": "codex-heartbeat-backfill",
        "action": "hold",
        "reason": "signal_conditions_not_met",
        "signal": {
            "date": "2026-04-24",
            "close": 659.1,
            "previous_close": 651.4,
            "sma_value": 600.054175,
            "rsi_value": 73.55010522723049,
            "is_down_day": False,
            "above_sma": True,
            "rsi_below_threshold": False,
            "should_open_put": False,
        },
        "positions": [],
        "candidate": None,
        "order_preview": None,
        "place_order_requested": True,
        "dry_run": False,
        "order_submitted": False,
    },
    {
        "timestamp": "2026-04-28T10:09:01-04:00",
        "source": "codex-heartbeat-backfill",
        "action": "hold",
        "reason": "signal_conditions_not_met",
        "signal": {
            "date": "2026-04-28",
            "close": 658.52,
            "previous_close": 664.28,
            "sma_value": 601.164625,
            "rsi_value": 70.00057615129299,
            "is_down_day": True,
            "above_sma": True,
            "rsi_below_threshold": False,
            "should_open_put": False,
        },
        "positions": [],
        "candidate": None,
        "order_preview": None,
        "place_order_requested": True,
        "dry_run": False,
        "order_submitted": False,
    },
    {
        "timestamp": "2026-04-29T11:57:58-04:00",
        "source": "codex-heartbeat-backfill",
        "action": "hold",
        "reason": "signal_conditions_not_met",
        "signal": {
            "date": "2026-04-29",
            "close": 661.59,
            "previous_close": 657.59,
            "sma_value": 601.697625,
            "rsi_value": 70.70426440379183,
            "is_down_day": False,
            "above_sma": True,
            "rsi_below_threshold": False,
            "should_open_put": False,
        },
        "positions": [],
        "candidate": None,
        "order_preview": None,
        "place_order_requested": True,
        "dry_run": False,
        "order_submitted": False,
    },
    {
        "timestamp": "2026-04-30T10:10:04-04:00",
        "source": "codex-heartbeat-backfill",
        "action": "hold",
        "reason": "signal_conditions_not_met",
        "signal": {
            "date": "2026-04-30",
            "close": 659.05,
            "previous_close": 661.59,
            "sma_value": 602.219575,
            "rsi_value": 68.4903207360807,
            "is_down_day": True,
            "above_sma": True,
            "rsi_below_threshold": False,
            "should_open_put": False,
        },
        "positions": [],
        "candidate": None,
        "order_preview": None,
        "place_order_requested": True,
        "dry_run": False,
        "order_submitted": False,
    },
    {
        "timestamp": "2026-05-04T10:09:43-04:00",
        "source": "codex-heartbeat-backfill",
        "action": "hold",
        "reason": "signal_conditions_not_met",
        "signal": {
            "date": "2026-05-04",
            "close": 674.77,
            "previous_close": 674.1,
            "sma_value": 603.432025,
            "rsi_value": 75.07697944240584,
            "is_down_day": False,
            "above_sma": True,
            "rsi_below_threshold": False,
            "should_open_put": False,
        },
        "positions": [],
        "candidate": None,
        "order_preview": None,
        "place_order_requested": True,
        "dry_run": False,
        "order_submitted": False,
    },
    {
        "timestamp": "2026-05-05T09:40:07-04:00",
        "source": "codex-heartbeat-backfill",
        "action": "hold",
        "reason": "signal_conditions_not_met",
        "signal": {
            "date": "2026-05-05",
            "close": 679.49,
            "previous_close": 672.78,
            "sma_value": 604.023675,
            "rsi_value": 75.81167370873295,
            "is_down_day": False,
            "above_sma": True,
            "rsi_below_threshold": False,
            "should_open_put": False,
        },
        "positions": [],
        "candidate": None,
        "order_preview": None,
        "place_order_requested": True,
        "dry_run": False,
        "order_submitted": False,
    },
    {
        "timestamp": "2026-05-07T10:09:01-04:00",
        "source": "codex-heartbeat-backfill",
        "action": "hold",
        "reason": "signal_conditions_not_met",
        "signal": {
            "date": "2026-05-07",
            "close": 698.485,
            "previous_close": 695.62,
            "sma_value": 605.398,
            "rsi_value": 80.69122187833642,
            "is_down_day": False,
            "above_sma": True,
            "rsi_below_threshold": False,
            "should_open_put": False,
        },
        "positions": [],
        "candidate": None,
        "order_preview": None,
        "place_order_requested": True,
        "dry_run": False,
        "order_submitted": False,
    },
    {
        "timestamp": "2026-05-08T03:08:41-04:00",
        "source": "codex-heartbeat-backfill",
        "action": "hold",
        "reason": "signal_conditions_not_met",
        "signal": {
            "date": "2026-05-08",
            "close": 711.12,
            "previous_close": 694.93,
            "sma_value": 606.127275,
            "rsi_value": 82.88127765072768,
            "is_down_day": False,
            "above_sma": True,
            "rsi_below_threshold": False,
            "should_open_put": False,
        },
        "positions": [],
        "candidate": None,
        "order_preview": None,
        "place_order_requested": True,
        "dry_run": False,
        "order_submitted": False,
    },
    {
        "timestamp": "2026-05-11T11:26:41-04:00",
        "source": "codex-heartbeat-backfill",
        "action": "hold",
        "reason": "signal_conditions_not_met",
        "signal": {
            "date": "2026-05-11",
            "close": 712.75,
            "previous_close": 711.12,
            "sma_value": 606.8759249999999,
            "rsi_value": 83.18969189629024,
            "is_down_day": False,
            "above_sma": True,
            "rsi_below_threshold": False,
            "should_open_put": False,
        },
        "positions": [],
        "candidate": None,
        "order_preview": None,
        "place_order_requested": True,
        "dry_run": False,
        "order_submitted": False,
    },
    {
        "timestamp": "2026-05-12T10:18:43-04:00",
        "source": "codex-heartbeat-backfill",
        "action": "hold",
        "reason": "signal_conditions_not_met",
        "signal": {
            "date": "2026-05-12",
            "close": 707.42,
            "previous_close": 713.37,
            "sma_value": 607.594375,
            "rsi_value": 77.829469640531,
            "is_down_day": True,
            "above_sma": True,
            "rsi_below_threshold": False,
            "should_open_put": False,
        },
        "positions": [],
        "candidate": None,
        "order_preview": None,
        "place_order_requested": True,
        "dry_run": False,
        "order_submitted": False,
    },
]


def main() -> None:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
    settings = load_settings()
    for record in HISTORICAL_RECORDS:
        append_jsonl_log(settings, record)
        append_text_log(settings, record)
    print(f"Backfilled {len(HISTORICAL_RECORDS)} historical records into {settings.log_dir}")


if __name__ == "__main__":
    main()
